### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by ZsoZso0527** [Extrack-public/Beta-Testing#17]
### 📄 A description of the bug

the more button says +0

### 📘 Steps to reproduce

Join less than 50 servers and grab yourself

### 🙂 Expected behavior

asd

### 😮 Unexpected behavior

asd

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/62513059/139429620-6b3e62ec-43a5-4d22-8cb0-d04402f3ec9e.png)

### 💻 Computer Information

asd

**Comment by plastic-dev** [comment]
Fixed
